
function motor_main_config(this_block)

  % Revision History:
  %
  %   23-Aug-2025  (20:02 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\Users\fabus\Documents\tesis\model_composer_test\mpc_implicito1\W21Q7_sp\motor_main.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('motor_main');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;

  this_block.addSimulinkInport('ap_rst');
  this_block.addSimulinkInport('ap_start');
  this_block.addSimulinkInport('fc0_input_ap_vld');
  this_block.addSimulinkInport('r');
  this_block.addSimulinkInport('pos');
  this_block.addSimulinkInport('vel');

  this_block.addSimulinkOutport('ap_done');
  this_block.addSimulinkOutport('ap_idle');
  this_block.addSimulinkOutport('ap_ready');
  this_block.addSimulinkOutport('layer13_out');
  this_block.addSimulinkOutport('layer13_out_ap_vld');

  ap_done_port = this_block.port('ap_done');
  ap_done_port.setType('UFix_1_0');
  ap_done_port.useHDLVector(false);

  ap_idle_port = this_block.port('ap_idle');
  ap_idle_port.setType('UFix_1_0');
  ap_idle_port.useHDLVector(false);

  ap_ready_port = this_block.port('ap_ready');
  ap_ready_port.setType('UFix_1_0');
  ap_ready_port.useHDLVector(false);

  layer13_out_port = this_block.port('layer13_out');
  layer13_out_port.setType('Fix_21_14');

  layer13_out_ap_vld_port = this_block.port('layer13_out_ap_vld');
  layer13_out_ap_vld_port.setType('UFix_1_0');
  layer13_out_ap_vld_port.useHDLVector(false);


  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('ap_rst').width ~= 1)
      this_block.setError('Input data type for port "ap_rst" must have width=1.');
    end

    this_block.port('ap_rst').useHDLVector(false);

    if (this_block.port('ap_start').width ~= 1)
      this_block.setError('Input data type for port "ap_start" must have width=1.');
    end

    this_block.port('ap_start').useHDLVector(false);

    if (this_block.port('fc0_input_ap_vld').width ~= 1)
      this_block.setError('Input data type for port "fc0_input_ap_vld" must have width=1.');
    end

    this_block.port('fc0_input_ap_vld').useHDLVector(false);

    if (this_block.port('r').width ~= 21)
      this_block.setError('Input data type for port "r" must have width=21.');
    end

    if (this_block.port('pos').width ~= 21)
      this_block.setError('Input data type for port "pos" must have width=21.');
    end

    if (this_block.port('vel').width ~= 21)
      this_block.setError('Input data type for port "vel" must have width=21.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk_1','ce_1')
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

this_block.addFile('W21Q7_sp/motor_relu_ap_fixed_21_7_0_0_0_ap_fixed_21_7_0_0_0_relu_config13_s.v');
this_block.addFile('W21Q7_sp/motor_relu_ap_fixed_21_7_0_0_0_ap_fixed_21_7_0_0_0_relu_config10_s.v');
this_block.addFile('W21Q7_sp/motor_mul_21s_12ns_33_1_0.v');
this_block.addFile('W21Q7_sp/motor_mul_21s_15ns_36_1_0.v');
this_block.addFile('W21Q7_sp/motor_mul_21s_13s_34_1_0.v');
this_block.addFile('W21Q7_sp/motor_mul_21s_15s_36_1_0.v');
this_block.addFile('W21Q7_sp/motor_mul_21s_14ns_35_1_0.v');
this_block.addFile('W21Q7_sp/motor_mul_21s_16ns_37_1_0.v');
this_block.addFile('W21Q7_sp/motor_dense_latency_ap_fixed_21_7_0_0_0_ap_fixed_21_7_0_0_0_config11_s.v');
this_block.addFile('W21Q7_sp/motor_mul_21s_13ns_34_1_0.v');
this_block.addFile('W21Q7_sp/motor_relu_ap_fixed_21_7_0_0_0_ap_fixed_21_7_0_0_0_relu_config7_s.v');
this_block.addFile('W21Q7_sp/motor_relu_ap_fixed_21_7_0_0_0_ap_fixed_21_7_0_0_0_relu_config4_s.v');
this_block.addFile('W21Q7_sp/motor_mul_21s_16s_37_1_0.v');
this_block.addFile('W21Q7_sp/motor_dense_latency_ap_fixed_21_7_0_0_0_ap_fixed_21_7_0_0_0_config8_s.v');
this_block.addFile('W21Q7_sp/motor_dense_latency_ap_fixed_21_7_0_0_0_ap_fixed_21_7_0_0_0_config2_s.v');
this_block.addFile('W21Q7_sp/motor_mul_21s_14s_35_1_0.v');
this_block.addFile('W21Q7_sp/motor_dense_latency_ap_fixed_21_7_0_0_0_ap_fixed_21_7_0_0_0_config5_s.v');
this_block.addFile('W21Q7_sp/motor.v');
this_block.addFile('W21Q7_sp/motor_main.v');


return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 && uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

% This function converts the matlab array to VHDL array Style 
% and this is valid only in case of generic parameters. 
function arrayHDLType = convertArrayType(inArr) 
arrayHDLType = '';
for i=1:length(inArr)
    if (i == 1)
        arrayHDLType = [arrayHDLType '(' num2str(inArr(i))]; 
    elseif (i == length(inArr)) 
        arrayHDLType = [arrayHDLType ',' num2str(inArr(i)) ')']; 
    else 
        arrayHDLType = [arrayHDLType ',' num2str(inArr(i))]; 
    end 
end 
