
function der1_config(this_block)

  % Revision History:
  %
  %   11-Dec-2025  (22:51 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\Users\fabus\Documents\tesis\matlab_cosim_der\der1_res\der1.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('der1');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;

  this_block.addSimulinkInport('ap_rst');
  this_block.addSimulinkInport('ap_start');
  this_block.addSimulinkInport('fc0_input_ap_vld');
  this_block.addSimulinkInport('sin_theta');
  this_block.addSimulinkInport('cos_theta');
  this_block.addSimulinkInport('rk11');
  this_block.addSimulinkInport('dk12');
  this_block.addSimulinkInport('dk11');
  this_block.addSimulinkInport('x14');
  this_block.addSimulinkInport('x13');
  this_block.addSimulinkInport('x12');
  this_block.addSimulinkInport('x11');

  this_block.addSimulinkOutport('ap_done');
  this_block.addSimulinkOutport('ap_idle');
  this_block.addSimulinkOutport('ap_ready');
  this_block.addSimulinkOutport('uk11');
  this_block.addSimulinkOutport('uk11_ap_vld');
  this_block.addSimulinkOutport('uk12');
  this_block.addSimulinkOutport('uk12_ap_vld');

  ap_done_port = this_block.port('ap_done');
  ap_done_port.setType('UFix_1_0');
  ap_done_port.useHDLVector(false);

  ap_idle_port = this_block.port('ap_idle');
  ap_idle_port.setType('UFix_1_0');
  ap_idle_port.useHDLVector(false);

  ap_ready_port = this_block.port('ap_ready');
  ap_ready_port.setType('UFix_1_0');
  ap_ready_port.useHDLVector(false);

  uk11_port = this_block.port('uk11');
  uk11_port.setType('Fix_22_14');

  uk11_ap_vld_port = this_block.port('uk11_ap_vld');
  uk11_ap_vld_port.setType('UFix_1_0');
  uk11_ap_vld_port.useHDLVector(false);

  uk12_port = this_block.port('uk12');
  uk12_port.setType('Fix_22_14');

  uk12_ap_vld_port = this_block.port('uk12_ap_vld');
  uk12_ap_vld_port.setType('UFix_1_0');
  uk12_ap_vld_port.useHDLVector(false);


  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('ap_rst').width ~= 1)
      this_block.setError('Input data type for port "ap_rst" must have width=1.');
    end

    this_block.port('ap_rst').useHDLVector(false);

    if (this_block.port('ap_start').width ~= 1)
      this_block.setError('Input data type for port "ap_start" must have width=1.');
    end

    this_block.port('ap_start').useHDLVector(false);

    if (this_block.port('fc0_input_ap_vld').width ~= 1)
      this_block.setError('Input data type for port "fc0_input_ap_vld" must have width=1.');
    end

    this_block.port('fc0_input_ap_vld').useHDLVector(false);

    if (this_block.port('sin_theta').width ~= 22)
      this_block.setError('Input data type for port "sin_theta" must have width=22.');
    end

    if (this_block.port('cos_theta').width ~= 22)
      this_block.setError('Input data type for port "cos_theta" must have width=22.');
    end

    if (this_block.port('rk11').width ~= 22)
      this_block.setError('Input data type for port "rk11" must have width=22.');
    end

    if (this_block.port('dk12').width ~= 22)
      this_block.setError('Input data type for port "dk12" must have width=22.');
    end

    if (this_block.port('dk11').width ~= 22)
      this_block.setError('Input data type for port "dk11" must have width=22.');
    end

    if (this_block.port('x14').width ~= 22)
      this_block.setError('Input data type for port "x14" must have width=22.');
    end

    if (this_block.port('x13').width ~= 22)
      this_block.setError('Input data type for port "x13" must have width=22.');
    end

    if (this_block.port('x12').width ~= 22)
      this_block.setError('Input data type for port "x12" must have width=22.');
    end

    if (this_block.port('x11').width ~= 22)
      this_block.setError('Input data type for port "x11" must have width=22.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk_1','ce_1')
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);

  % (!) Custimize the following generic settings as appropriate. If any settings depend
  %      on input types, make the settings in the "inputTypesKnown" code block.
  %      The addGeneric function takes  3 parameters, generic name, type and constant value.
  %      Supported types are boolean, real, integer and string.
  % NOTE: Use the "convertArrayType" API in case of real_vector/integer_vector. 
  this_block.addGeneric('ap_ST_fsm_pp0_stage0','integer','1');
  this_block.addGeneric('ap_ST_fsm_pp0_stage1','integer','2');

  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

this_block.addFile('der1_res/der_mul_22s_13s_34_1_1.v');
this_block.addFile('der1_res/der_mul_22s_14ns_36_1_1.v');
this_block.addFile('der1_res/der_relu_ap_fixed_22_8_0_0_0_ap_fixed_22_8_0_0_0_relu_config10_s.v');
this_block.addFile('der1_res/der_mul_22s_17s_38_1_1.v');
this_block.addFile('der1_res/der_relu_ap_fixed_22_8_0_0_0_ap_fixed_22_8_0_0_0_relu_config16_s.v');
this_block.addFile('der1_res/der_mul_22s_15ns_37_1_1.v');
this_block.addFile('der1_res/der_mul_22s_19s_40_1_1.v');
this_block.addFile('der1_res/der_relu_ap_fixed_22_8_0_0_0_ap_fixed_22_8_0_0_0_relu_config13_s.v');
this_block.addFile('der1_res/der_mul_22s_16s_37_1_1.v');
this_block.addFile('der1_res/der_mul_22s_14s_35_1_1.v');
this_block.addFile('der1_res/der_mul_22s_11s_32_1_1.v');
this_block.addFile('der1_res/der_mul_22s_13ns_35_1_1.v');
this_block.addFile('der1_res/der_mul_22s_17s_39_1_1.v');
this_block.addFile('der1_res/der_mul_22s_12s_34_1_1.v');
this_block.addFile('der1_res/der_mul_22s_16ns_38_1_1.v');
this_block.addFile('der1_res/der_mul_22s_15s_37_1_1.v');
this_block.addFile('der1_res/der_mul_22s_15s_36_1_1.v');
this_block.addFile('der1_res/der_mul_22s_18ns_40_1_1.v');
this_block.addFile('der1_res/der_mul_22s_17ns_39_1_1.v');
this_block.addFile('der1_res/der_mul_22s_16s_38_1_1.v');
this_block.addFile('der1_res/der_mul_22s_12ns_34_1_1.v');
this_block.addFile('der1_res/der_mul_22s_11ns_33_1_1.v');
this_block.addFile('der1_res/der_relu_ap_fixed_22_8_0_0_0_ap_fixed_22_8_0_0_0_relu_config4_s.v');
this_block.addFile('der1_res/der_mul_22s_19s_41_1_1.v');
this_block.addFile('der1_res/der_mul_22s_18s_39_1_1.v');
this_block.addFile('der1_res/der_mul_22s_18s_40_1_1.v');
this_block.addFile('der1_res/der_dense_latency_ap_fixed_22_8_0_0_0_ap_fixed_22_8_0_0_0_config14_s.v');
this_block.addFile('der1_res/der_relu_ap_fixed_22_8_0_0_0_ap_fixed_22_8_0_0_0_relu_config7_s.v');
this_block.addFile('der1_res/der_mul_22s_14s_36_1_1.v');
this_block.addFile('der1_res/der_mul_22s_13s_35_1_1.v');
this_block.addFile('der1_res/der_dense_latency_ap_fixed_22_8_0_0_0_ap_fixed_22_8_0_0_0_config11_s.v');
this_block.addFile('der1_res/der_dense_latency_ap_fixed_22_8_0_0_0_ap_fixed_22_8_0_0_0_config2_s.v');
this_block.addFile('der1_res/der_dense_latency_ap_fixed_22_8_0_0_0_ap_fixed_22_8_0_0_0_config8_s.v');
this_block.addFile('der1_res/der_dense_latency_ap_fixed_22_8_0_0_0_ap_fixed_22_8_0_0_0_config5_s.v');
this_block.addFile('der1_res/der1.v');


return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 && uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

% This function converts the matlab array to VHDL array Style 
% and this is valid only in case of generic parameters. 
function arrayHDLType = convertArrayType(inArr) 
arrayHDLType = '';
for i=1:length(inArr)
    if (i == 1)
        arrayHDLType = [arrayHDLType '(' num2str(inArr(i))]; 
    elseif (i == length(inArr)) 
        arrayHDLType = [arrayHDLType ',' num2str(inArr(i)) ')']; 
    else 
        arrayHDLType = [arrayHDLType ',' num2str(inArr(i))]; 
    end 
end 
