function F_ = fi_config(W,Q)
    
    wordLength = W;
    fracLength = W-Q;
        F_ = fimath('OverflowAction', 'Saturate', ... 
       'RoundingMethod', 'Convergent', ...
       'ProductMode', 'SpecifyPrecision', ...
       'ProductWordLength', wordLength, ...
       'ProductFractionLength', fracLength, ...
       'SumMode', 'SpecifyPrecision', ...
       'SumWordLength', wordLength, ...
       'SumFractionLength', fracLength);