
W_qt = coder.const(12);
Q_qt = coder.const(5);
wordLength = coder.const(W_qt);
fracLength = coder.const(W_qt-Q_qt);
F_ = coder.const(fimath('OverflowAction', 'Saturate', ... 
   'RoundingMethod', 'Convergent', ...
   'ProductMode', 'SpecifyPrecision', ...
   'ProductWordLength', wordLength, ...
   'ProductFractionLength', fracLength, ...
   'SumMode', 'SpecifyPrecision', ...
   'SumWordLength', wordLength, ...
   'SumFractionLength', fracLength));

h5_file = "fixed_model_matlab.h5";
DNN =  init_net_fixedL4(h5_file,W_qt, Q_qt, F_);
csv_file_out = ("data_out_fixedDNN.csv");
data_in =  readmatrix("data_in.csv");
data_in = data_in';
results = eval_net_fixedL4(data_in,DNN)';

writematrix(results, csv_file_out);