Backend: Vitis
ClockPeriod: 10
HLSConfig:
  LayerName:
    fc0:
      Precision:
        bias: fixed<16,7>
        result: fixed<16,7,RND,SAT>
        weight: fixed<16,7>
      Trace: true
    fc0_input:
      Precision:
        result: fixed<16,7,RND,SAT>
      Trace: true
    fc0_linear:
      Precision:
        result: fixed<16,7,RND,SAT>
      Trace: true
    fc1:
      Precision:
        bias: fixed<16,7>
        result: fixed<16,7,RND,SAT>
        weight: fixed<16,7>
      Trace: true
    fc1_linear:
      Precision:
        result: fixed<16,7,RND,SAT>
      Trace: true
    fc2:
      Precision:
        bias: fixed<16,7>
        result: fixed<16,7,RND,SAT>
        weight: fixed<16,7>
      Trace: true
    fc2_linear:
      Precision:
        result: fixed<16,7,RND,SAT>
      Trace: true
    fc3:
      Precision:
        bias: fixed<16,7>
        result: fixed<16,7,RND,SAT>
        weight: fixed<16,7>
      Trace: true
    fc3_linear:
      Precision:
        result: fixed<16,7,RND,SAT>
      Trace: true
    relu0:
      Precision:
        result: fixed<16,7,RND,SAT>
      Trace: true
    relu1:
      Precision:
        result: fixed<16,7,RND,SAT>
      Trace: true
    relu2:
      Precision:
        result: fixed<16,7,RND,SAT>
      Trace: true
    relu3:
      Precision:
        result: fixed<16,7,RND,SAT>
      Trace: true
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,7,RND,SAT>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: true
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'HLS_exp/motorB_L3M9W16Q7_sparse/motorB/keras_model.h5'
OutputDir: HLS_exp/motorB_L3M9W16Q7_sparse/motorB
OutputPredictions: null
Part: xc7k325tfbg900-1
ProjectName: motor
Stamp: 62294c28
Version: 1.0.0
